# Use the official Neo4j image
FROM neo4j:latest

# Set environment variable for initial authentication.
ENV NEO4J_AUTH=neo4j/SamsungGalaxy2526

# Expose the web browser port and the Bolt protocol port
EXPOSE 7474 7687
